apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv
  namespace: smartaquaculture
spec:
  authentication: 
    path: kubernetes
    role: kv-engine-admin
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  type: kv
  path: aitelemetry
