apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-setup-defaults
  namespace: prom-keycloak-proxy
data:
  main.yaml: |
    
    ######################
    # OpenShift defaults #
    ######################

    # The wildcard domain suffix where OpenShift Routes are available by default. 
    OPENSHIFT_APPS_DOMAIN: "{{ lookup('env', 'OPENSHIFT_APPS_DOMAIN') | default('apps-crc.testing', true) }}"

    #############
    # Site vars #
    #############

    # The name of this application. 
    SITE_NAME: "prom-keycloak-proxy"
    # The short name of this application. 
    SITE_SHORT_NAME: "promkeycloakproxy"
    # The site namespace in OpenShift. 
    SITE_NAMESPACE: "{{ lookup('env', 'SITE_NAMESPACE') | default('prom-keycloak-proxy', true) }}"

    #####################################
    # Authentication/authorization vars #
    #####################################

    # The namespace in OpenShift where Keycloak will run. 
    AUTH_NAMESPACE: "{{ lookup('env', 'AUTH_NAMESPACE_' + SITE_SHORT_NAME) | default('keycloak', true) }}"
    # The Auth host name. 
    AUTH_HOST_NAME: "{{ lookup('env', 'AUTH_HOST_NAME_' + SITE_SHORT_NAME) | default('keycloak.' + OPENSHIFT_APPS_DOMAIN, true) }}"
    # The Auth port. 
    AUTH_PORT: 443
    # Whether the Auth server uses SSL. 
    AUTH_SSL: true
    # Whether the Auth server requires SSL. 
    AUTH_SSL_REQUIRED: "all"
    # The Auth realm. 
    AUTH_REALM: "{{ lookup('env', 'AUTH_REALM_' + SITE_SHORT_NAME) | default('AITELEMETRY' | upper, true) }}"
    # The Auth client. 
    AUTH_CLIENT: "{{ lookup('env', 'AUTH_CLIENT_' + SITE_SHORT_NAME) | default('aitelemetry', true) }}"
    # The Auth openshift secret with the client secret credentials. 
    AUTH_ADMIN_OPENSHIFT_SECRET: "{{ lookup('env', 'AUTH_ADMIN_OPENSHIFT_SECRET_' + SITE_SHORT_NAME) | default('keycloak-initial-admin', true) }}"
    # The Auth admin username. 
    AUTH_ADMIN_USERNAME: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=AUTH_ADMIN_OPENSHIFT_SECRET, namespace=AUTH_NAMESPACE)[0].data['username'] | b64decode }}"
    # The Auth admin password. 
    AUTH_ADMIN_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=AUTH_ADMIN_OPENSHIFT_SECRET, namespace=AUTH_NAMESPACE)[0].data['password'] | b64decode }}"
    # The Auth URL. 
    AUTH_URL: "https://keycloak.apps-crc.testing"
    # The Auth URL to retrieve tokens. 
    AUTH_TOKEN_URI: "/realms/{{ AUTH_REALM }}/protocol/openid-connect/token"
    # Enables authorization fine-grained resource permissions. 
    AUTH_FINE_GRAINED_POLICY_PERMISSIONS: true

    #######################
    # prom-keycloak-proxy #
    #######################
    # Whether to use SSL when connecting to the Prometheus Keycloak Proxy. 
    PROM_KEYCLOAK_PROXY_SSL: "{{ (lookup('env', 'PROM_KEYCLOAK_PROXY_SSL') | lower) != 'false' }}"
    # The host name to connect to the Prometheus Keycloak Proxy in OpenShift. 
    PROM_KEYCLOAK_PROXY_HOST_NAME: "{{ lookup('env', 'PROM_KEYCLOAK_PROXY_HOST_NAME') | default('prom-keycloak-proxy.' + OPENSHIFT_APPS_DOMAIN, true) }}"
    # The default port that the Prometheus Keycloak Proxy runs. 
    PROM_KEYCLOAK_PROXY_PORT: "{{ lookup('env', 'PROM_KEYCLOAK_PROXY_PORT') | default('443', true) }}"
