apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-setup-openshift-monitoring-tasks
  namespace: vault
data:
  main.yaml: |
    ---
    - name: Set vault pod name
      set_fact:
        VAULT_POD: "vault-0"
    - block:
        - name: Initialize vault
          kubernetes.core.k8s_exec:
            namespace: "{{ VAULT_NAMESPACE }}"
            pod: "{{ VAULT_POD }}"
            command: >-
              vault operator init -address http://vault.vault.svc.cluster.local:8200 -ca-path /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt -format=json -key-shares 1 -key-threshold 1
          register: vault_init
          ignore_errors: true
        - debug:
            var: vault_init
        - name: Get vault init dev secrets
          set_fact:
            VAULT_UNSEAL_KEY: >-
              {{ vault_init.stdout | regex_search('"unseal_keys_b64":\s*\[\s*"([^"]+)"', '\1') | first }}
            VAULT_ROOT_TOKEN: >-
              {{ vault_init.stdout | regex_search('"root_token":\s*"([^"]+)"', '\1') | first }}
          when: not vault_init.failed
      when: VAULT_UNSEAL_KEY is not defined and VAULT_ROOT_TOKEN is not defined or VAULT_UNSEAL_KEY == '' and VAULT_ROOT_TOKEN == ''

    - name: Get vault init dev secrets
      set_fact:
        VAULT_UNSEAL_KEY: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='vault-init', namespace=VAULT_NAMESPACE, validate_certs=false)[0].data.VAULT_UNSEAL_KEY | b64decode }}"
        VAULT_ROOT_TOKEN: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='vault-init', namespace=VAULT_NAMESPACE, validate_certs=false)[0].data.VAULT_ROOT_TOKEN | b64decode }}"
      when: VAULT_UNSEAL_KEY is not defined and VAULT_ROOT_TOKEN is not defined or VAULT_UNSEAL_KEY == '' and VAULT_ROOT_TOKEN == ''

    - block:
        - name: Write vault secret-reader-openshift-monitoring policy
          kubernetes.core.k8s_exec:
            namespace: "{{ VAULT_NAMESPACE }}"
            pod: "{{ VAULT_POD }}"
            command: >-
              bash -c 'echo '"'"'{{ lookup('template', 'secret-reader-openshift-monitoring-policy.hcl') | regex_replace('\\{\\{', '{{', multiline=True) | regex_replace('\\}\\}', '}}', multiline=True) }}'"'"' | env VAULT_TOKEN="{{ VAULT_ROOT_TOKEN }}" vault policy write -tls-skip-verify secret-reader-openshift-monitoring -'
          register: vault_write_secret_reader_policy
          ignore_errors: true
        - name: Write vault kv-engine-admin-openshift-monitoring policy
          kubernetes.core.k8s_exec:
            namespace: "{{ VAULT_NAMESPACE }}"
            pod: "{{ VAULT_POD }}"
            command: >-
              bash -c 'echo '"'"'{{ lookup('template', 'kv-engine-admin-openshift-monitoring-policy.hcl') | regex_replace('\\{\\{', '{{', multiline=True) | regex_replace('\\}\\}', '}}', multiline=True) }}'"'"' | env VAULT_TOKEN="{{ VAULT_ROOT_TOKEN }}" vault policy write -tls-skip-verify kv-engine-admin-openshift-monitoring -'
          register: vault_write_kv_engine_admin_policy
          ignore_errors: true
        - debug:
            var: vault_write_kv_engine_admin_policy
