apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-setup-openshift-monitoring-templates
  namespace: vault
data:
  secret-reader-openshift-monitoring-policy.hcl: |
    # read secrets
    path "/openshift-monitoring/kv/*" {
      capabilities = [ "read" ]
    }
  kv-engine-admin-openshift-monitoring-policy.hcl: |
    # query existing mounts
    path "/sys/mounts" {
      capabilities = [ "list", "read"]
      allowed_parameters = {
        "type" = ["database"]
        "*"   = []
      }
    }
    # mount database kv engines
    path "/sys/mounts/openshift-monitoring/kv-openshift-monitoring" {
      capabilities = [ "create", "read", "update", "delete", "list" ]
      allowed_parameters = {
        "type" = ["kv"]
        "*"   = []
      }
    }
    # tune database secrets engines
    path "/sys/mounts/openshift-monitoring/kv/tune" {
      capabilities = [ "create", "read", "update", "delete"]
    }
