apiVersion: batch/v1
kind: Job
metadata:
  name: time-zone-import
  namespace: aitelemetry
spec:
  backoffLimit: 1000
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: time-zone-import
        env:
          - name: ENABLE_ZOOKEEPER_CLUSTER
            value: 'true'
          - name: CLUSTER_HOST_NAME
            value: 0.0.0.0
          - name: CLUSTER_PORT
            value: '10211'
          - name: CLUSTER_PUBLIC_HOST_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: CLUSTER_PUBLIC_PORT
            value: '10211'
          - name: IMPORT_DATA_ONCE
            value: 'true'
          - name: ENABLE_IMPORT_DATA_TimeZone
            value: 'true'
        envFrom:
        - secretRef:
            name: cloud-zookeeper
        - secretRef:
            name: cloud-solr
        - secretRef:
            name: cloud-database
        - secretRef:
            name: cloud-auth
        - secretRef:
            name: cloud-context-broker
        - secretRef:
            name: cloud-site
        - secretRef:
            name: cloud-font-awesome
        - secretRef:
            name: cloud-extra
        image: quay.io/nerc-images/ai-telemetry:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
          requests:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
        ports:
        - containerPort: 10211
          name: cluster
          protocol: TCP
        command: ["/bin/bash", "-c", "--"]
        args:
          - >-
              java -cp "$(cat /home/default/ai-telemetry/cp.txt):/home/default/ai-telemetry/target/classes" org.mghpcc.aitelemetry.verticle.WorkerVerticle
