apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aitelemetry-secrets/
  - cloud-setup/
  - aitelemetry/
  - openshift-monitoring/
  - prom-keycloak-proxy-secrets/
  - prom-keycloak-proxy-cloud-setup/
  - prom-keycloak-proxy-local-cluster/
